format = """
[  ](bg:#ffffff fg:#090c0c)\
[](bg:#b1b1b1 fg:#ffffff)\
$directory\
[](fg:#b1b1b1 bg:#7e7e7e)\
$git_branch\
$git_status\
[](fg:#7e7e7e bg:#454545)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#454545 bg:#000000)\
$time\
[ ](fg:#000000)\
\n$character"""

[directory]
style = "fg:#000000 bg:#b1b1b1 "
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#ffffff bg:#7e7e7e)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#ffffff bg:#7e7e7e)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#ffffff bg:#454545)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time ](fg:#ffffff bg:#000000)]($style)'

[character]
success_symbol = '[➜](bold white)'
